// <auto-generated />
namespace BeYourMarket.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class promail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(promail));
        
        string IMigrationMetadata.Id
        {
            get { return "201812190304105_promail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
